projects:
  app:
    schemaPath: 'src/schema.graphql'
    extensions:
      endpoints:
        default: 'https://jeepney-yoga.herokuapp.com'
  prisma:
    schemaPath: 'src/generated/prisma.graphql'
    extensions:
      prisma: prisma.yml
